# Generated by Django 2.2.4 on 2023-06-07 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 17, 19, 0, 430868)),
        ),
        migrations.AddField(
            model_name='shows',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 17, 19, 0, 430868)),
        ),
    ]
