# Generated by Django 2.2.4 on 2023-06-07 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0002_auto_20230607_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 17, 20, 40, 288908)),
        ),
        migrations.AlterField(
            model_name='shows',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 17, 20, 40, 288908)),
        ),
    ]
