# Generated by Django 2.2.4 on 2023-06-08 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0004_auto_20230607_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 3, 27, 10, 510550)),
        ),
        migrations.AlterField(
            model_name='shows',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 3, 27, 10, 510550)),
        ),
    ]
