# Generated by Django 2.2.4 on 2023-06-08 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0005_auto_20230608_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='title',
        ),
        migrations.AlterField(
            model_name='shows',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 3, 48, 26, 69135)),
        ),
        migrations.AlterField(
            model_name='shows',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 3, 48, 26, 69135)),
        ),
    ]
