# Generated by Django 2.2.4 on 2023-06-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0002_remove_shows_show_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='updated_at',
        ),
    ]
