# Generated by Django 2.2.4 on 2023-06-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0003_auto_20230608_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='show_desc',
            new_name='show_descAAAAAAAAAAAAA',
        ),
    ]
