# Generated by Django 2.2.4 on 2023-06-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0005_auto_20230608_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='show_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='shows',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
