# Generated by Django 2.2.4 on 2023-06-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0004_auto_20230608_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='show_descAAAAAAAAAAAAA',
            new_name='show_desc',
        ),
    ]
